# sudo docker compose up -d --build --force-recreate
services:
    redis-master:
        image: redis:latest
        container_name: redis-master
        restart: unless-stopped
        command: redis-server --loglevel warning --requirepass _password_ --masterauth _password_ --replica-announce-ip 192.168.29.242 --replica-announce-port 6379
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"
    redis-slave:
        image: redis:latest
        container_name: redis-slave
        restart: unless-stopped
        command: redis-server --slaveof redis-master 6379 --loglevel warning --requirepass _password_ --masterauth _password_ --replica-announce-ip 192.168.29.242  --replica-announce-port 6378
        links:
            - redis-master
        volumes:
            - redis-data:/data
        ports:
            - "6378:6379"
    redis-sentinel1:
        build:
            context: ./redis-sentinel
        depends_on:
            - redis-master
            - redis-slave
        environment:
            - REDIS_MASTER_PASSWORD='_password_'
        ports:
            - "26377:26379"
    redis-sentinel2:
        build:
            context: ./redis-sentinel
        depends_on:
            - redis-master
            - redis-slave
        environment:
            - REDIS_MASTER_PASSWORD='_password_'
        ports:
            - "26378:26379"
    redis-sentinel3:
        build:
            context: ./redis-sentinel
        depends_on:
            - redis-master
            - redis-slave
        environment:
            - REDIS_MASTER_PASSWORD='_password_'
        ports:
            - "26379:26379"
volumes:
    redis-data:
    redis-conf:
